### ISSUE TITLE
Support for multiple host running in parallel

### ISSUE THREAD

**Issue by jcoufal** [rdo-management/inlunch#1]

**Comment by jcoufal** [comment]
... Ideally through CLI

**Comment by jistr** [comment]
It's in. No need to create a hosts file now if you don't want, and you can select a different location of answerfile too, if you want to run different hosts with different answer files in parallel.

See the tricks section in readme for usage info:

https://github.com/rdo-management/inlunch/blob/84d1583990f3431381aeedb41808d27672193127/README.md#tricks-for-instack-virtsh

**Comment by jistr** [comment]
Implemented in
https://github.com/rdo-management/inlunch/commit/73a8595c603abe0b2e1e0bd9f15ca300b070437a
