### ISSUE TITLE
Support for stop-after-virt-setup

### ISSUE THREAD

**Issue by jcoufal** [rdo-management/inlunch#2]

**Comment by jcoufal** [comment]
Might be good to consider including all flow steps in the answers file and let user enter break-point wherever he wants. This gives him great freedom and he can stop wherever he wants without hardly finding what is the flow and before/after which step he has to stop.

**Comment by jistr** [comment]
Added stopping points `after_instack_virt_setup` and `after_undercloud_forwarding` and refactored how they're used in answer file. See the the example answer file for new usage:

https://github.com/rdo-management/inlunch/blob/84d1583990f3431381aeedb41808d27672193127/answers.yml.example#L76-L86

**Comment by jistr** [comment]
Implemented in https://github.com/rdo-management/inlunch/commit/36205148dd92cbb94590dd4ea1ab4c64b70b1d7e and https://github.com/rdo-management/inlunch/commit/6de9c3e8ccea21f0543bcfbd68affd369cfab2b3
