### ISSUE TITLE
Remove old instack IP address after instack-virt-destroy.sh

### ISSUE THREAD

**Issue by jcoufal** [rdo-management/inlunch#4]
instack-virt.sh  ->  instack-virt-destroy.sh  ->  instack-virt.sh
arp -n

--------------------------------
result: two IP addresses listed, would be nice to get rid of the old one, otherwise it will be cumulating.

**Comment by jistr** [comment]
Querying the arp cache is probably not the best way to find the IP. Inlunch now creates an `undercloud-ip.sh` script to stack user's home directory on the host machine. It queries libvirt IP leases instead.

```bash
[stack@hp-dl180gen9-01 ~]$ ./undercloud-ip.sh 
192.168.122.177
```

**Comment by jistr** [comment]
Implemented in https://github.com/rdo-management/inlunch/commit/9a4a4809dbb7739fcbf15bf9abcd1732c8ee77da
